import type { Category, Order, Product } from "./types";

export const PRODUCTS: Product[] = [
  {
    id: "lg-gp2",
    sku: "LG-GP2",
    cat: "mice",
    catLabel: "MICE",
    brand: "Logitech G",
    name: "PRO X SUPERLIGHT 2",
    fullName: "Logitech G PRO X SUPERLIGHT 2",
    blurb: "Mouse · 60 g · 8 K Hz polling",
    long: "A 60-gram wireless competition mouse. Magnesium internal frame, Hero 2 sensor, hybrid optical-mechanical switches.",
    price: 159,
    msrp: null,
    stock: "ok",
    stockLabel: "IN STOCK · SHIPS MON",
    verified: true,
    badge: null,
    art: "mouse",
    specs: [
      ["Sensor", "Hero 2 · 32 000 DPI"],
      ["Polling", "8 000 Hz"],
      ["Weight", "60 g"],
      ["Switches", "Lightforce hybrid optical-mechanical"],
      ["Battery", "95 hr · USB-C"],
      ["Connectivity", "Lightspeed 2.4 GHz · USB-C wired"],
      ["Warranty", "2 yr"],
    ],
    swatches: {
      COLOR: ["Black", "Bone", "Red"],
      WEIGHT: ["60 g · stock", "63 g · grip tape"],
    },
  },
  {
    id: "rog-az",
    sku: "ROG-AZ-FG",
    cat: "keyboards",
    catLabel: "KEYBOARDS",
    brand: "ASUS ROG",
    name: "Azoth × FG Edition",
    fullName: "ROG Azoth × FG Anniversary Edition",
    blurb: "75% · gasket mount · hot-swap",
    long: "75% wireless deck. Gasket-mounted, hot-swap PCB, doubleshot PBT keycaps, OLED display, tri-mode connectivity.",
    price: 329,
    msrp: 349,
    stock: "warn",
    stockLabel: "LOW · 3 LEFT",
    verified: false,
    badge: { type: "ignit", label: "LIMITED · 042 / 500" },
    art: "keyboard",
    specs: [
      ["Layout", "75% · 81 keys"],
      ["Switches", "ROG NX Snow V2 · linear · 40 g"],
      ["Mount", "Gasket · silicone dampening"],
      ["Keycaps", "Doubleshot PBT · MDA profile"],
      ["Connectivity", "2.4 GHz · BT 5.2 · USB-C"],
      ["Battery", "2 000 mAh · 60 hr RGB off"],
      ["Warranty", "2 yr"],
    ],
    swatches: {
      SWITCH: ["Linear · 40 g", "Tactile · 55 g", "Clicky · 55 g"],
      LAYOUT: ["60%", "75%", "TKL"],
    },
  },
  {
    id: "he-emb",
    sku: "HE-EMB-G",
    cat: "chairs",
    catLabel: "CHAIRS",
    brand: "Herman Miller × Logitech G",
    name: "Embody Gaming",
    fullName: "Herman Miller × Logitech G Embody Gaming Chair",
    blurb: "Chair · Carbon · 12 yr warranty",
    long: "Pixelated back support that conforms to your spine. Aeron-grade build with cooling tech and a 12-year warranty.",
    price: 1495,
    msrp: null,
    stock: "err",
    stockLabel: "BACKORDER · 3 WKS",
    verified: true,
    badge: null,
    art: "chair",
    specs: [
      ["Back", "BackFit · pixelated support"],
      ["Material", "Sync Fabric · cooling foam"],
      ["Tilt", "5-position recline · 95–120°"],
      ["Adjust", "Seat depth · armrest 4D · lumbar"],
      ["Weight cap", "136 kg"],
      ["Warranty", "12 yr"],
    ],
    swatches: { COLOR: ["Carbon", "Galaxy", "Glacier"] },
  },
  {
    id: "sb-ar",
    sku: "SB-AR4",
    cat: "headsets",
    catLabel: "HEADSETS",
    brand: "SteelSeries",
    name: "Arctis Nova Pro Wireless",
    fullName: "SteelSeries Arctis Nova Pro Wireless",
    blurb: "Headset · ANC · dual battery",
    long: "Hi-Res certified driver, active noise cancellation, dual-battery hot-swap base station — no cables, no downtime.",
    price: 379,
    msrp: 419,
    stock: "ok",
    stockLabel: "IN STOCK",
    verified: true,
    badge: { type: "volt", label: "NEW" },
    art: "headset",
    specs: [
      ["Drivers", "40 mm Hi-Res certified neodymium"],
      ["Frequency", "10 Hz – 40 kHz"],
      ["Mic", "ClearCast Gen 2 · retractable"],
      ["ANC", "Active · 4-mic hybrid"],
      ["Connectivity", "2.4 GHz · BT 5.0 · USB-C"],
      ["Battery", "2 × swappable · 22 hr each"],
    ],
    swatches: { COLOR: ["Black", "White"] },
  },
  {
    id: "sd-r3",
    sku: "SD-R3",
    cat: "desks",
    catLabel: "DESKS",
    brand: "Secretlab",
    name: "Magnus Pro XL",
    fullName: "Secretlab Magnus Pro XL Sit/Stand",
    blurb: "Desk · sit/stand · 1.8 m",
    long: "Magnetic ecosystem desk. Dual-motor sit/stand frame, full-surface magnetic cable tray, and a metal mat that snaps in.",
    price: 1149,
    msrp: null,
    stock: "ok",
    stockLabel: "IN STOCK",
    verified: false,
    badge: null,
    art: "desk",
    specs: [
      ["Surface", "1.8 m × 0.8 m · steel"],
      ["Range", "69 cm – 122 cm · dual motor"],
      ["Capacity", "120 kg"],
      ["Memory", "4 height presets"],
      ["Cable", "Magnetic full-width tray"],
    ],
    swatches: { SIZE: ["1.5 m", "1.8 m"], COLOR: ["Black", "Bone"] },
  },
  {
    id: "ra-vp",
    sku: "RA-VPR",
    cat: "mice",
    catLabel: "MICE",
    brand: "Razer",
    name: "Viper V3 Pro",
    fullName: "Razer Viper V3 Pro",
    blurb: "Mouse · 54 g · symmetrical",
    long: "Razer's lightest pro mouse. Focus Pro 35K sensor, 8 K Hz native polling, ambidextrous shell.",
    price: 169,
    msrp: null,
    stock: "ok",
    stockLabel: "IN STOCK",
    verified: true,
    art: "mouse",
    specs: [
      ["Sensor", "Focus Pro 35K"],
      ["Polling", "8 000 Hz"],
      ["Weight", "54 g"],
      ["Battery", "95 hr"],
    ],
    swatches: { COLOR: ["Black", "White"] },
  },
  {
    id: "wb-q",
    sku: "WB-Q1",
    cat: "keyboards",
    catLabel: "KEYBOARDS",
    brand: "Wooting",
    name: "60HE+",
    fullName: "Wooting 60HE+ Analog Keyboard",
    blurb: "60% · analog hall-effect",
    long: "Adjustable-actuation analog hall-effect keyboard. Per-key actuation point, rapid trigger, controller-grade input.",
    price: 199,
    msrp: null,
    stock: "ok",
    stockLabel: "IN STOCK",
    verified: true,
    badge: { type: "volt", label: "PRO PICK" },
    art: "keyboard",
    specs: [
      ["Layout", "60% · 61 keys"],
      ["Switches", "Lekker · hall-effect analog"],
      ["Actuation", "0.1 – 4.0 mm adjustable"],
      ["Rapid trigger", "Yes · 0.1 mm reset"],
      ["Polling", "8 000 Hz"],
    ],
    swatches: { COLOR: ["Black", "White"] },
  },
  {
    id: "fc-ke",
    sku: "FC-KE2",
    cat: "chairs",
    catLabel: "CHAIRS",
    brand: "Secretlab",
    name: "TITAN Evo NanoGen",
    fullName: "Secretlab TITAN Evo NanoGen",
    blurb: "Chair · NeoHybrid · 5 yr",
    long: "The classic gaming chair, refined. NeoHybrid leatherette, magnetic memory-foam head pillow, 4-way lumbar.",
    price: 649,
    msrp: 729,
    stock: "ok",
    stockLabel: "IN STOCK",
    verified: false,
    art: "chair",
    specs: [
      ["Upholstery", "NeoHybrid leatherette"],
      ["Recline", "85–165°"],
      ["Lumbar", "4-way adjustable"],
      ["Capacity", "129 kg"],
      ["Warranty", "5 yr"],
    ],
    swatches: {
      SIZE: ["S", "R", "XL"],
      COLOR: ["Stealth", "Onyx", "Plush Pink"],
    },
  },
];

export const CATEGORIES: Category[] = [
  { id: "chairs", name: "Chairs", count: 14, art: "chair" },
  { id: "desks", name: "Desks", count: 8, art: "desk" },
  { id: "keyboards", name: "Keyboards", count: 32, art: "keyboard" },
  { id: "mice", name: "Mice", count: 18, art: "mouse" },
  { id: "headsets", name: "Headsets", count: 22, art: "headset" },
  { id: "accessories", name: "Accessories", count: 60, art: "controller" },
];

export const ORDERS: Order[] = [
  {
    id: "0029",
    date: "12 May 2026",
    status: "Shipped",
    total: 488,
    items: 2,
    tracking: "DHL EA-2087-91X",
    preview: ["mouse", "headset"],
  },
  {
    id: "0014",
    date: "02 Apr 2026",
    status: "Delivered",
    total: 1495,
    items: 1,
    tracking: "—",
    preview: ["chair"],
  },
  {
    id: "0007",
    date: "18 Feb 2026",
    status: "Delivered",
    total: 199,
    items: 1,
    tracking: "—",
    preview: ["keyboard"],
  },
];

export function byId(id: string): Product | undefined {
  return PRODUCTS.find((p) => p.id === id);
}

export function byCat(cat: string): Product[] {
  return PRODUCTS.filter((p) => p.cat === cat);
}

export const INITIAL_CART_IDS = ["lg-gp2", "sb-ar"];
