import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

const b = (type: string, label: string) => JSON.stringify({ type, label });
const sp = (pairs: [string, string][]) => JSON.stringify(pairs);
const sw = (obj: Record<string, string[]>) => JSON.stringify(obj);

const products = [
  // ─────────────────────────────────────────────────────
  //  MICE
  // ─────────────────────────────────────────────────────
  {
    id: "logitech-g-pro-x-superlight-2",
    sku: "HG-MO-001",
    catId: "mice",
    catLabel: "Mice",
    brand: "Logitech G",
    name: "Pro X Superlight 2",
    fullName: "Logitech G Pro X Superlight 2",
    blurb: "59 g · HERO 2 sensor · 300 h battery",
    description:
      "The G Pro X Superlight 2 is the lightest pro mouse Logitech has ever built. At 59 g it disappears in your hand, and the HERO 2 sensor tracks at up to 32,000 DPI with zero smoothing or filtering. Dual LIGHTSPEED receivers, 300-hour battery, and a PTFE-coated base that glides on any surface.",
    price: 159,
    msrp: null,
    stock: "ok",
    stockLabel: "In Stock",
    quantity: 14,
    imageUrl: null,
    verified: true,
    badge: null,
    art: "mouse",
    specs: sp([
      ["Weight", "59 g"],
      ["Sensor", "HERO 2 · 25,600 DPI max"],
      ["Connection", "LIGHTSPEED Wireless"],
      ["Battery", "300 hours"],
      ["Buttons", "5"],
      ["Polling rate", "1,000 Hz"],
      ["Cable", "None (wireless)"],
    ]),
    swatches: sw({ Color: ["White", "Black"] }),
  },
  {
    id: "razer-deathadder-v3-pro",
    sku: "HG-MO-002",
    catId: "mice",
    catLabel: "Mice",
    brand: "Razer",
    name: "DeathAdder V3 Pro",
    fullName: "Razer DeathAdder V3 Pro",
    blurb: "63 g · Focus Pro 30K · 90 h battery",
    description:
      "The iconic DeathAdder shape, completely re-engineered. The V3 Pro shaves 25% of the weight off its predecessor while keeping the ergonomic right-hand form that millions of players trust. Focus Pro 30K optical sensor, Razer HyperSpeed wireless, and 90-hour battery.",
    price: 139,
    msrp: 169,
    stock: "ok",
    stockLabel: "In Stock",
    quantity: 22,
    imageUrl: null,
    verified: false,
    badge: b("ignit", "SALE"),
    art: "mouse",
    specs: sp([
      ["Weight", "63 g"],
      ["Sensor", "Focus Pro 30K · 30,000 DPI"],
      ["Connection", "HyperSpeed Wireless / USB-C"],
      ["Battery", "90 hours"],
      ["Buttons", "5"],
      ["Polling rate", "1,000 Hz"],
      ["Scroll", "Optical scroll"],
    ]),
    swatches: sw({ Color: ["Black", "White"] }),
  },
  {
    id: "asus-rog-harpe-ace",
    sku: "HG-MO-003",
    catId: "mice",
    catLabel: "Mice",
    brand: "ASUS ROG",
    name: "Harpe Ace Aim Lab Edition",
    fullName: "ASUS ROG Harpe Ace Aim Lab Edition",
    blurb: "54 g · 36K sensor · ROG SpeedNova",
    description:
      "Tuned alongside Aim Lab's data scientists, the Harpe Ace uses real heatmap analysis from 20 million players to land on a shape that fits the widest range of grip styles at 54 g. ROG SpeedNova wireless technology and the AimPoint Pro 36K optical sensor make it one of the most technically complete mice available.",
    price: 149,
    msrp: 179,
    stock: "ok",
    stockLabel: "In Stock",
    quantity: 9,
    imageUrl: null,
    verified: true,
    badge: b("ignit", "SALE"),
    art: "mouse",
    specs: sp([
      ["Weight", "54 g"],
      ["Sensor", "AimPoint Pro · 36,000 DPI"],
      ["Connection", "ROG SpeedNova Wireless / USB-C"],
      ["Battery", "100 hours"],
      ["Buttons", "6"],
      ["Polling rate", "8,000 Hz (via adapter)"],
    ]),
    swatches: null,
  },
  {
    id: "zowie-ec2-c",
    sku: "HG-MO-004",
    catId: "mice",
    catLabel: "Mice",
    brand: "Zowie",
    name: "EC2-C",
    fullName: "Zowie EC2-C",
    blurb: "73 g · 3360 sensor · plug-and-play",
    description:
      "No drivers. No software. No RGB. The EC2-C is plug-and-play gaming precision — the 3360 sensor, a symmetric ergonomic right-hand shell, and pure wired performance. The EC2-C is the mouse that lets you focus entirely on the game.",
    price: 79,
    msrp: null,
    stock: "ok",
    stockLabel: "In Stock",
    quantity: 31,
    imageUrl: null,
    verified: false,
    badge: null,
    art: "mouse",
    specs: sp([
      ["Weight", "73 g"],
      ["Sensor", "PMW 3360 · 3,200 DPI"],
      ["Connection", "USB-A wired"],
      ["Cable", "Rubber · 2 m"],
      ["Buttons", "5"],
      ["Polling rate", "1,000 Hz"],
      ["Grips", "Side rubber grips"],
    ]),
    swatches: null,
  },
  {
    id: "endgame-gear-xm2we",
    sku: "HG-MO-005",
    catId: "mice",
    catLabel: "Mice",
    brand: "Endgame Gear",
    name: "XM2we",
    fullName: "Endgame Gear XM2we",
    blurb: "70 g · PAW 3395 · 150 h battery",
    description:
      "Built in collaboration with the esports community, the XM2we brings the ultra-low-latency XM2w platform to a wider audience at an accessible price. PAW 3395 sensor with genuine 26,000 DPI resolution, 150-hour battery, and a symmetrical shell that suits both palm and claw grip.",
    price: 89,
    msrp: 109,
    stock: "warn",
    stockLabel: "Low Stock",
    quantity: 3,
    imageUrl: null,
    verified: false,
    badge: b("ignit", "SALE"),
    art: "mouse",
    specs: sp([
      ["Weight", "70 g"],
      ["Sensor", "PAW 3395 · 26,000 DPI"],
      ["Connection", "2.4 GHz Wireless / USB-C"],
      ["Battery", "150 hours"],
      ["Buttons", "6"],
      ["Polling rate", "1,000 Hz"],
    ]),
    swatches: sw({ Color: ["Black", "White"] }),
  },
  {
    id: "steelseries-aerox-5-wireless",
    sku: "HG-MO-006",
    catId: "mice",
    catLabel: "Mice",
    brand: "SteelSeries",
    name: "Aerox 5 Wireless",
    fullName: "SteelSeries Aerox 5 Wireless",
    blurb: "74 g · TrueMove Air · 180 h battery",
    description:
      "Nine programmable buttons in a 74 g wireless shell. The Aerox 5 Wireless is built for MMO and MOBA players who want a featherlight mouse without sacrificing button count. The AquaBarrier coating keeps dust and water out while the honeycomb shell keeps weight down.",
    price: 119,
    msrp: 149,
    stock: "ok",
    stockLabel: "In Stock",
    quantity: 17,
    imageUrl: null,
    verified: false,
    badge: b("ignit", "SALE"),
    art: "mouse",
    specs: sp([
      ["Weight", "74 g"],
      ["Sensor", "TrueMove Air · 18,000 DPI"],
      ["Connection", "2.4 GHz Wireless / USB-C"],
      ["Battery", "180 hours"],
      ["Buttons", "9"],
      ["Polling rate", "1,000 Hz"],
      ["Rating", "IPX4 splash-resistant"],
    ]),
    swatches: null,
  },

  // ─────────────────────────────────────────────────────
  //  KEYBOARDS
  // ─────────────────────────────────────────────────────
  {
    id: "wooting-60he-plus",
    sku: "HG-KB-001",
    catId: "keyboards",
    catLabel: "Keyboards",
    brand: "Wooting",
    name: "60HE+",
    fullName: "Wooting 60HE+",
    blurb: "60% · Hall-effect · analog input",
    description:
      "The Wooting 60HE+ is the keyboard that redefined rapid trigger. Lekker Hall-effect switches detect magnet position instead of contact, enabling sub-0.1 mm actuation and rapid trigger that resets within fractions of a millimeter. The 60% layout keeps your mouse arm in a natural position.",
    price: 149,
    msrp: null,
    stock: "ok",
    stockLabel: "In Stock",
    quantity: 8,
    imageUrl: null,
    verified: true,
    badge: null,
    art: "keyboard",
    specs: sp([
      ["Form factor", "60%"],
      ["Switch", "Lekker L45 / L60 Hall-effect"],
      ["Actuation", "0.1–4.0 mm (configurable)"],
      ["Rapid trigger", "Yes · 0.1 mm resolution"],
      ["Connection", "USB-C"],
      ["RGB", "Per-key RGB"],
      ["Mount", "Top mount"],
    ]),
    swatches: sw({ Switch: ["Lekker L45 (Linear)", "Lekker L60 (Linear)"] }),
  },
  {
    id: "asus-rog-azoth-extreme",
    sku: "HG-KB-002",
    catId: "keyboards",
    catLabel: "Keyboards",
    brand: "ASUS ROG",
    name: "Azoth Extreme",
    fullName: "ASUS ROG Azoth Extreme",
    blurb: "75% · Tri-mode wireless · gasket mount",
    description:
      "The ROG Azoth Extreme takes the acclaimed Azoth platform and adds tri-mode wireless (RF 2.4 GHz, Bluetooth 5.3, USB-C), a precision OLED display with rotary encoder, and a premium gasket mount with PCB foam dampening. The NX Snow linear switches come factory-lubed.",
    price: 299,
    msrp: 349,
    stock: "ok",
    stockLabel: "In Stock",
    quantity: 5,
    imageUrl: null,
    verified: true,
    badge: b("ignit", "SALE"),
    art: "keyboard",
    specs: sp([
      ["Form factor", "75%"],
      ["Switch", "ROG NX Snow (Linear, pre-lubed)"],
      ["Connection", "RF 2.4 GHz / BT 5.3 / USB-C"],
      ["Battery", "~2,000 mAh"],
      ["Display", "OLED status display"],
      ["Mount", "Gasket + PCB foam"],
      ["RGB", "Per-key AURA Sync"],
    ]),
    swatches: sw({
      Switch: ["NX Snow (Linear)", "NX Red (Linear)", "NX Blue (Clicky)"],
    }),
  },
  {
    id: "keychron-q1-max",
    sku: "HG-KB-003",
    catId: "keyboards",
    catLabel: "Keyboards",
    brand: "Keychron",
    name: "Q1 Max",
    fullName: "Keychron Q1 Max",
    blurb: "75% · QMK/VIA · wireless aluminum",
    description:
      "Full anodized aluminum body, gasket mount, QMK and VIA support with wireless capability — the Q1 Max is for builders who refuse to compromise. The south-facing PCB is compatible with virtually every keycap set, and the dual-mode Bluetooth keeps your desk clean.",
    price: 199,
    msrp: null,
    stock: "ok",
    stockLabel: "In Stock",
    quantity: 12,
    imageUrl: null,
    verified: true,
    badge: null,
    art: "keyboard",
    specs: sp([
      ["Form factor", "75%"],
      ["Body", "Full anodized aluminum"],
      ["Switch", "Gateron G Pro 3.0 (your choice)"],
      ["Connection", "Bluetooth 5.1 / USB-C"],
      ["Firmware", "QMK + VIA"],
      ["Mount", "Gasket"],
      ["RGB", "South-facing per-key"],
    ]),
    swatches: sw({
      Switch: ["Red (Linear)", "Brown (Tactile)", "Blue (Clicky)"],
      Color: ["Carbon Black", "Space Grey", "Navy Blue"],
    }),
  },
  {
    id: "razer-blackwidow-v4-75",
    sku: "HG-KB-004",
    catId: "keyboards",
    catLabel: "Keyboards",
    brand: "Razer",
    name: "BlackWidow V4 75%",
    fullName: "Razer BlackWidow V4 75%",
    blurb: "75% · Yellow switches · HyperSpeed wireless",
    description:
      "The BlackWidow V4 75% brings Razer's flagship mechanical keyboard into a compact wireless form factor. Razer Yellow linear switches are factory-lubed and rated for 100 million keystrokes. HyperSpeed wireless at 1 ms latency with a dedicated dongle slot on the USB hub.",
    price: 169,
    msrp: 199,
    stock: "ok",
    stockLabel: "In Stock",
    quantity: 19,
    imageUrl: null,
    verified: false,
    badge: b("ignit", "SALE"),
    art: "keyboard",
    specs: sp([
      ["Form factor", "75%"],
      ["Switch", "Razer Yellow (Linear, pre-lubed)"],
      ["Connection", "HyperSpeed 2.4 GHz / BT / USB-C"],
      ["Battery", "~4,000 mAh"],
      ["Actuation", "1.2 mm"],
      ["Total travel", "4.0 mm"],
      ["RGB", "Razer Chroma per-key"],
    ]),
    swatches: sw({ Switch: ["Yellow (Linear)", "Green (Clicky)"] }),
  },
  {
    id: "steelseries-apex-pro-tkl-wireless",
    sku: "HG-KB-005",
    catId: "keyboards",
    catLabel: "Keyboards",
    brand: "SteelSeries",
    name: "Apex Pro TKL Wireless",
    fullName: "SteelSeries Apex Pro TKL Wireless",
    blurb: "TKL · OmniPoint 2.0 · adjustable actuation",
    description:
      "OmniPoint 2.0 Hall-effect switches let you set actuation from 0.1 mm to 4.0 mm per key individually. The Apex Pro TKL Wireless is the most configurable mechanical keyboard on the market, with an OLED smart display, per-key RGB, and a full-aluminum frame in a tenkeyless package.",
    price: 199,
    msrp: 229,
    stock: "ok",
    stockLabel: "In Stock",
    quantity: 7,
    imageUrl: null,
    verified: true,
    badge: b("ignit", "SALE"),
    art: "keyboard",
    specs: sp([
      ["Form factor", "TKL (80%)"],
      ["Switch", "OmniPoint 2.0 Adjustable HE"],
      ["Actuation", "0.1–4.0 mm (per key)"],
      ["Connection", "2.4 GHz / USB-C"],
      ["Display", "OLED Smart Display"],
      ["Battery", "200 hours"],
      ["RGB", "Per-key Prism RGB"],
    ]),
    swatches: null,
  },
  {
    id: "corsair-k70-pro-mini",
    sku: "HG-KB-006",
    catId: "keyboards",
    catLabel: "Keyboards",
    brand: "Corsair",
    name: "K70 Pro Mini Wireless",
    fullName: "Corsair K70 Pro Mini Wireless",
    blurb: "60% · Cherry MX Speed · AXON 4K polling",
    description:
      "The K70 Pro Mini is Corsair's most compact wireless keyboard, featuring Cherry MX Speed switches and iCUE's AXON technology for 4,000 Hz polling rate — four times the industry standard. Full RGB backlighting and the K70 series' iconic aluminum top case in 60% form.",
    price: 129,
    msrp: 159,
    stock: "warn",
    stockLabel: "Low Stock",
    quantity: 2,
    imageUrl: null,
    verified: false,
    badge: b("ignit", "SALE"),
    art: "keyboard",
    specs: sp([
      ["Form factor", "60%"],
      ["Switch", "Cherry MX Speed Silver"],
      ["Connection", "Slipstream 2.4 GHz / BT / USB-C"],
      ["Polling rate", "4,000 Hz (AXON)"],
      ["Battery", "200 hours"],
      ["RGB", "Per-key iCUE"],
      ["Body", "Anodized aluminum"],
    ]),
    swatches: sw({ Switch: ["Speed Silver (Linear)", "Red (Linear)", "Blue (Clicky)"] }),
  },

  // ─────────────────────────────────────────────────────
  //  CHAIRS
  // ─────────────────────────────────────────────────────
  {
    id: "secretlab-titan-evo-2022",
    sku: "HG-CH-001",
    catId: "chairs",
    catLabel: "Chairs",
    brand: "Secretlab",
    name: "Titan Evo 2022",
    fullName: "Secretlab Titan Evo 2022",
    blurb: "Cloud® foam · 4-way lumbar · Neo™ Hybrid",
    description:
      "The Titan Evo 2022 is Secretlab's flagship chair, featuring their proprietary Cloud™ foam that's 20% softer than memory foam while retaining shape over years of use. The integrated 4-way L-ADAPT lumbar system adjusts to your spine's natural curve. Neo™ Hybrid Leatherette is 12x more durable than PU leather.",
    price: 449,
    msrp: 529,
    stock: "ok",
    stockLabel: "In Stock",
    quantity: 11,
    imageUrl: null,
    verified: true,
    badge: b("ignit", "SALE"),
    art: "chair",
    specs: sp([
      ["Foam", "Secretlab Cloud™ proprietary"],
      ["Lumbar", "4-way L-ADAPT integrated"],
      ["Material", "Neo™ Hybrid Leatherette"],
      ["Armrests", "4D with magnetic top"],
      ["Recline", "85–165°"],
      ["Weight limit", "130 kg"],
      ["Height", "Fits 157–189 cm"],
    ]),
    swatches: sw({ Size: ["S", "Regular", "XL"], Color: ["Stealth Black", "Ash", "Frost Blue"] }),
  },
  {
    id: "herman-miller-embody-logitech",
    sku: "HG-CH-002",
    catId: "chairs",
    catLabel: "Chairs",
    brand: "Herman Miller",
    name: "Embody Gaming × Logitech G",
    fullName: "Herman Miller Embody Gaming × Logitech G",
    blurb: "PostureFit SL · Backfit™ · 12-year warranty",
    description:
      "The Herman Miller Embody Gaming chair is engineered with NASA-studied spine support. Its PostureFit SL sacral and lumbar support system aligns the lower and upper back simultaneously. The Backfit™ adjustment mechanism tilts the backrest to match the angle of your pelvis — adapted for the forward lean of gaming with cooling foam inserts.",
    price: 1499,
    msrp: null,
    stock: "ok",
    stockLabel: "In Stock",
    quantity: 4,
    imageUrl: null,
    verified: true,
    badge: null,
    art: "chair",
    specs: sp([
      ["Spine support", "PostureFit SL (sacral + lumbar)"],
      ["Backfit", "Adjustable pixel matrix back"],
      ["Armrests", "4D"],
      ["Recline", "94–104° with harmonic tilt"],
      ["Weight limit", "136 kg"],
      ["Warranty", "12 years"],
      ["Cooling", "Copper-infused cooling foam"],
    ]),
    swatches: sw({ Color: ["Black / Logitech Blue", "Mineral Blue"] }),
  },
  {
    id: "sense7-spellcaster",
    sku: "HG-CH-003",
    catId: "chairs",
    catLabel: "Chairs",
    brand: "SENSE7",
    name: "Spellcaster",
    fullName: "SENSE7 Spellcaster",
    blurb: "Adjustable lumbar · steel frame · class-4 gas",
    description:
      "The SENSE7 Spellcaster gives you ergonomic gaming seating at an accessible price. A solid steel frame, class-4 gas cylinder, 3D armrests, and adjustable lumbar pillow — all at a price that won't break the bank. The split-design backrest allows independent left/right movement for a more natural sitting experience.",
    price: 109,
    msrp: 277,
    stock: "ok",
    stockLabel: "In Stock",
    quantity: 28,
    imageUrl: null,
    verified: false,
    badge: b("ignit", "SALE"),
    art: "chair",
    specs: sp([
      ["Frame", "Steel"],
      ["Gas cylinder", "Class 4"],
      ["Armrests", "3D"],
      ["Lumbar", "Adjustable pillow"],
      ["Recline", "90–150°"],
      ["Weight limit", "120 kg"],
      ["Height", "Fits 160–185 cm"],
    ]),
    swatches: sw({ Color: ["Black", "Black/Red", "Black/Blue"] }),
  },
  {
    id: "corsair-tc60-fabric",
    sku: "HG-CH-004",
    catId: "chairs",
    catLabel: "Chairs",
    brand: "Corsair",
    name: "TC60 Fabric",
    fullName: "Corsair TC60 Fabric",
    blurb: "Breathable fabric · memory foam · 4D arms",
    description:
      "The TC60 Fabric replaces faux leather with a breathable woven fabric shell for cooler gaming sessions. High-density foam lumbar pillow, memory foam neck pillow, and 4D armrests that adjust front, back, left, right, and height independently. A steel internal frame and class-4 gas lift are included as standard.",
    price: 199,
    msrp: 249,
    stock: "ok",
    stockLabel: "In Stock",
    quantity: 16,
    imageUrl: null,
    verified: false,
    badge: b("ignit", "SALE"),
    art: "chair",
    specs: sp([
      ["Material", "Breathable fabric"],
      ["Foam", "Memory foam lumbar + neck pillows"],
      ["Armrests", "4D"],
      ["Recline", "85–160°"],
      ["Frame", "Steel"],
      ["Gas cylinder", "Class 4"],
      ["Weight limit", "120 kg"],
    ]),
    swatches: sw({ Color: ["Charcoal", "Grey"] }),
  },

  // ─────────────────────────────────────────────────────
  //  DESKS
  // ─────────────────────────────────────────────────────
  {
    id: "flexispot-e7-pro",
    sku: "HG-DK-001",
    catId: "desks",
    catLabel: "Desks",
    brand: "Flexispot",
    name: "E7 Pro Standing Desk",
    fullName: "Flexispot E7 Pro Standing Desk",
    blurb: "Dual motor · 100 kg load · anti-collision",
    description:
      "The Flexispot E7 Pro is one of the most stable sit-stand desks at its price point. Dual brushless motors lift up to 100 kg across a 60–125 cm height range in near silence. The keypad has 4 programmable presets, and the anti-collision system stops instantly on contact. Solid steel frame with a wobble-free cross brace.",
    price: 449,
    msrp: 549,
    stock: "ok",
    stockLabel: "In Stock",
    quantity: 6,
    imageUrl: null,
    verified: true,
    badge: b("ignit", "SALE"),
    art: "desk",
    specs: sp([
      ["Height range", "60–125 cm"],
      ["Motor", "Dual brushless"],
      ["Lifting capacity", "100 kg"],
      ["Noise", "< 45 dB"],
      ["Presets", "4 programmable"],
      ["Anti-collision", "Yes"],
      ["Frame warranty", "15 years"],
    ]),
    swatches: sw({
      Size: ["120×60 cm", "140×70 cm", "160×80 cm"],
      Top: ["White", "Black", "Maple", "Bamboo"],
    }),
  },
  {
    id: "sense7-nomad-electric",
    sku: "HG-DK-002",
    catId: "desks",
    catLabel: "Desks",
    brand: "SENSE7",
    name: "Nomad Electric 140 cm",
    fullName: "SENSE7 Nomad Electric 140 cm",
    blurb: "Electric sit-stand · cable management",
    description:
      "The SENSE7 Nomad Electric offers sit-stand functionality at an entry-level price. A single-motor column raises and lowers the 140 cm top across a 72–117 cm range, with 3 memory presets and a built-in cable management tray that keeps your setup clean. MDF top with ABS edge banding.",
    price: 299,
    msrp: 399,
    stock: "ok",
    stockLabel: "In Stock",
    quantity: 9,
    imageUrl: null,
    verified: false,
    badge: b("ignit", "SALE"),
    art: "desk",
    specs: sp([
      ["Width", "140 cm"],
      ["Height range", "72–117 cm"],
      ["Motor", "Single"],
      ["Lifting capacity", "70 kg"],
      ["Presets", "3"],
      ["Top material", "MDF + ABS edge"],
      ["Cable tray", "Included"],
    ]),
    swatches: sw({ Color: ["Black", "White"] }),
  },
  {
    id: "uplift-v2-standing-desk",
    sku: "HG-DK-003",
    catId: "desks",
    catLabel: "Desks",
    brand: "Uplift",
    name: "V2 Standing Desk",
    fullName: "Uplift V2 Standing Desk",
    blurb: "ANSI/BIFMA · 7-year warranty · advanced keypad",
    description:
      "The Uplift V2 is ANSI/BIFMA certified for commercial use and comes with a 7-year warranty on the frame and electronics. Dual-motor lifting system handles up to 160 kg, and the advanced keypad supports 4 height presets, sit/stand reminders, and a lock function. Sourced and assembled in North America.",
    price: 549,
    msrp: null,
    stock: "ok",
    stockLabel: "In Stock",
    quantity: 3,
    imageUrl: null,
    verified: true,
    badge: null,
    art: "desk",
    specs: sp([
      ["Height range", "64–129 cm"],
      ["Motor", "Dual"],
      ["Lifting capacity", "160 kg"],
      ["Certification", "ANSI/BIFMA"],
      ["Presets", "4 + reminder"],
      ["Frame warranty", "7 years"],
      ["Assembly", "North America"],
    ]),
    swatches: sw({
      Size: ["120×60 cm", "150×75 cm", "180×80 cm"],
      Top: ["Eco Curve", "Solid Bamboo", "Rubberwood"],
    }),
  },

  // ─────────────────────────────────────────────────────
  //  HEADSETS
  // ─────────────────────────────────────────────────────
  {
    id: "steelseries-arctis-nova-pro-wireless",
    sku: "HG-HS-001",
    catId: "headsets",
    catLabel: "Headsets",
    brand: "SteelSeries",
    name: "Arctis Nova Pro Wireless",
    fullName: "SteelSeries Arctis Nova Pro Wireless",
    blurb: "Hi-Res audio · ANC · dual-battery base",
    description:
      "The Arctis Nova Pro Wireless is the most technically advanced gaming headset SteelSeries has made. Hi-Res certified 40 mm drivers, Active Noise Cancellation, a 24-hour battery with hot-swap dual-battery system (so you never need to stop playing), and a base station that connects simultaneously to PC and console.",
    price: 349,
    msrp: 399,
    stock: "ok",
    stockLabel: "In Stock",
    quantity: 8,
    imageUrl: null,
    verified: true,
    badge: b("ignit", "SALE"),
    art: "headset",
    specs: sp([
      ["Drivers", "40 mm Hi-Res certified"],
      ["Connection", "2.4 GHz + Bluetooth 5.0"],
      ["Battery", "Dual hot-swap · 24 h each"],
      ["ANC", "Active Noise Cancellation"],
      ["Mic", "Retractable ClearCast Gen 2"],
      ["Base station", "Multi-device · USB + optical"],
      ["Response range", "10–40,000 Hz"],
    ]),
    swatches: null,
  },
  {
    id: "hyperx-cloud-alpha-wireless",
    sku: "HG-HS-002",
    catId: "headsets",
    catLabel: "Headsets",
    brand: "HyperX",
    name: "Cloud Alpha Wireless",
    fullName: "HyperX Cloud Alpha Wireless",
    blurb: "300 h battery · dual-chamber drivers",
    description:
      "300-hour battery life is the headline, but the Cloud Alpha Wireless has the audio to match. HyperX's dual-chamber drivers physically separate bass and mid-high frequencies to eliminate bleed, delivering cleaner positional audio. Memory foam ear cushions with leatherette lining keep long sessions comfortable.",
    price: 179,
    msrp: 219,
    stock: "ok",
    stockLabel: "In Stock",
    quantity: 24,
    imageUrl: null,
    verified: false,
    badge: b("ignit", "SALE"),
    art: "headset",
    specs: sp([
      ["Drivers", "50 mm dual-chamber"],
      ["Connection", "2.4 GHz USB"],
      ["Battery", "300 hours"],
      ["Frequency response", "15–21,000 Hz"],
      ["Mic type", "Detachable cardioid"],
      ["Ear cups", "Memory foam + leatherette"],
      ["Weight", "335 g"],
    ]),
    swatches: sw({ Color: ["Black / Red", "Black / Blue"] }),
  },
  {
    id: "logitech-g-pro-x2-lightspeed",
    sku: "HG-HS-003",
    catId: "headsets",
    catLabel: "Headsets",
    brand: "Logitech G",
    name: "Pro X 2 Lightspeed",
    fullName: "Logitech G Pro X 2 Lightspeed",
    blurb: "LIGHTSPEED · Blue VO!CE · graphene drivers",
    description:
      "The G Pro X 2 Lightspeed is endorsed by 50+ pro esports players across 10+ leagues. Graphene-reinforced drivers with a 40 mm diameter deliver precise audio with minimal distortion. LIGHTSPEED wireless matches the latency of a wired connection. Blue VO!CE microphone technology includes hardware reverb and three-band EQ.",
    price: 249,
    msrp: 299,
    stock: "ok",
    stockLabel: "In Stock",
    quantity: 12,
    imageUrl: null,
    verified: true,
    badge: b("ignit", "SALE"),
    art: "headset",
    specs: sp([
      ["Drivers", "40 mm graphene-reinforced"],
      ["Connection", "LIGHTSPEED 2.4 GHz / USB-C"],
      ["Battery", "50 hours"],
      ["Mic", "Blue VO!CE · cardioid"],
      ["Frequency response", "20–20,000 Hz"],
      ["Weight", "345 g"],
      ["Ear cups", "Memory foam (leatherette + velour included)"],
    ]),
    swatches: sw({ Color: ["Black", "White", "Lilac"] }),
  },
  {
    id: "razer-blackshark-v2-pro",
    sku: "HG-HS-004",
    catId: "headsets",
    catLabel: "Headsets",
    brand: "Razer",
    name: "BlackShark V2 Pro",
    fullName: "Razer BlackShark V2 Pro",
    blurb: "THX Spatial Audio · TriForce Titanium · 70 h",
    description:
      "The BlackShark V2 Pro features Razer's TriForce Titanium 50 mm drivers — three-part drivers that handle highs, mids, and lows independently. THX Spatial Audio provides certified 360° positional sound. The HyperClear Supercardioid mic has 4-pole pickup and real-time voice changer built in.",
    price: 179,
    msrp: 229,
    stock: "ok",
    stockLabel: "In Stock",
    quantity: 19,
    imageUrl: null,
    verified: false,
    badge: b("ignit", "SALE"),
    art: "headset",
    specs: sp([
      ["Drivers", "TriForce Titanium 50 mm"],
      ["Connection", "HyperSpeed 2.4 GHz / BT 5.2"],
      ["Battery", "70 hours"],
      ["Audio", "THX Spatial Audio"],
      ["Mic", "HyperClear Supercardioid detachable"],
      ["Ear cups", "FlowKnit memory foam"],
      ["Weight", "320 g"],
    ]),
    swatches: sw({ Color: ["Black", "White"] }),
  },
  {
    id: "asus-rog-delta-s-wireless",
    sku: "HG-HS-005",
    catId: "headsets",
    catLabel: "Headsets",
    brand: "ASUS ROG",
    name: "Delta S Wireless",
    fullName: "ASUS ROG Delta S Wireless",
    blurb: "AI noise cancellation · MQA audio · USB-C",
    description:
      "The ROG Delta S Wireless packs AI-powered noise cancellation, MQA audio decoding, and a USB-C receiver into a headset that works on PC, Mac, PlayStation, and Nintendo Switch. The quad-DAC design provides 130 dB signal-to-noise ratio, and the retractable microphone hides flush when not in use.",
    price: 149,
    msrp: 189,
    stock: "warn",
    stockLabel: "Low Stock",
    quantity: 3,
    imageUrl: null,
    verified: false,
    badge: b("ignit", "SALE"),
    art: "headset",
    specs: sp([
      ["Drivers", "AI-designed 50 mm"],
      ["Connection", "USB-C 2.4 GHz / BT 5.0"],
      ["DAC", "Quad-DAC · 130 dB SNR"],
      ["Audio", "MQA Hi-Res"],
      ["Battery", "25 hours"],
      ["Mic", "Retractable cardioid"],
      ["Platform", "PC / Mac / PS5 / Switch"],
    ]),
    swatches: null,
  },

  // ─────────────────────────────────────────────────────
  //  ACCESSORIES
  // ─────────────────────────────────────────────────────
  {
    id: "artisan-hayate-otsu-xl",
    sku: "HG-AC-001",
    catId: "accessories",
    catLabel: "Accessories",
    brand: "Artisan",
    name: "Hayate Otsu XL",
    fullName: "Artisan Hayate Otsu XL",
    blurb: "XL soft mat · mid-glide · stitched edge",
    description:
      "Artisan is the premier Japanese mousepad maker. The Hayate Otsu is their fastest cloth pad — a tight weave that provides low initial friction and consistent mid-glide across the entire surface. Stitched edges prevent fraying. XL size covers most desks and accommodates ultra-low sensitivities.",
    price: 59,
    msrp: null,
    stock: "ok",
    stockLabel: "In Stock",
    quantity: 42,
    imageUrl: null,
    verified: true,
    badge: null,
    art: "controller",
    specs: sp([
      ["Size", "490 × 420 × 4 mm"],
      ["Surface", "Cloth · tight weave"],
      ["Glide profile", "Mid-speed (control/speed balance)"],
      ["Base", "Natural rubber with micro-suction"],
      ["Edge", "Stitched"],
      ["Origin", "Japan"],
    ]),
    swatches: sw({ Color: ["Black", "White", "Pink"] }),
  },
  {
    id: "logitech-g-powerplay",
    sku: "HG-AC-002",
    catId: "accessories",
    catLabel: "Accessories",
    brand: "Logitech G",
    name: "POWERPLAY Wireless Charging System",
    fullName: "Logitech G POWERPLAY Wireless Charging System",
    blurb: "Charges while you play · LIGHTSPEED · 344×280 mm",
    description:
      "The Logitech G POWERPLAY mat charges compatible LIGHTSPEED mice continuously while in use. No interruptions, no cables to your mouse — the electromagnetic field passes through the cloth or hard surface module. Compatible with G Pro X Superlight, G502 X Plus, G703, G903, and more.",
    price: 109,
    msrp: 139,
    stock: "ok",
    stockLabel: "In Stock",
    quantity: 18,
    imageUrl: null,
    verified: false,
    badge: b("ignit", "SALE"),
    art: "controller",
    specs: sp([
      ["Size", "344 × 280 mm"],
      ["Charging", "Electromagnetic · continuous"],
      ["Compatible mice", "G Pro X SL, G502 X+, G703, G903"],
      ["Surface modules", "Cloth (included) + Hard (sold separately)"],
      ["RGB", "Logitech G LIGHTSYNC"],
      ["Cable", "USB-A · 1.8 m"],
    ]),
    swatches: null,
  },
  {
    id: "elgato-stream-deck-mk2",
    sku: "HG-AC-003",
    catId: "accessories",
    catLabel: "Accessories",
    brand: "Elgato",
    name: "Stream Deck MK.2",
    fullName: "Elgato Stream Deck MK.2",
    blurb: "15 LCD keys · one-touch streaming control",
    description:
      "Fifteen customizable LCD keys at your fingertips. The Stream Deck MK.2 puts scenes, sources, audio, and social platforms all within reach. Trigger actions in OBS, Streamlabs, Discord, Twitch, Spotify, and 100+ other tools. Detachable USB-C cable and removable faceplate for a clean setup.",
    price: 149,
    msrp: 179,
    stock: "ok",
    stockLabel: "In Stock",
    quantity: 27,
    imageUrl: null,
    verified: false,
    badge: b("ignit", "SALE"),
    art: "controller",
    specs: sp([
      ["Keys", "15 LCD customizable"],
      ["Key resolution", "72 × 72 px each"],
      ["Connection", "USB-C (detachable)"],
      ["Stand", "Adjustable tilt"],
      ["Software", "Elgato Stream Deck (free)"],
      ["Integrations", "OBS, Twitch, Discord, Spotify, 100+"],
      ["Platform", "Windows 10+ / macOS 10.15+"],
    ]),
    swatches: sw({ Color: ["Black", "White"] }),
  },
  {
    id: "corsair-mm700-rgb-extended",
    sku: "HG-AC-004",
    catId: "accessories",
    catLabel: "Accessories",
    brand: "Corsair",
    name: "MM700 RGB Extended",
    fullName: "Corsair MM700 RGB Extended",
    blurb: "930×400 mm · 360° RGB edge · 2-port USB hub",
    description:
      "The MM700 RGB Extended turns your desk into a command center. The 930×400 mm surface provides room for both your keyboard and mouse, and the 360° circumferential RGB edge lights up the room. A built-in 2-port USB hub routes through the braided cable so you can connect peripherals without reaching around to your tower.",
    price: 79,
    msrp: 99,
    stock: "ok",
    stockLabel: "In Stock",
    quantity: 34,
    imageUrl: null,
    verified: false,
    badge: b("ignit", "SALE"),
    art: "controller",
    specs: sp([
      ["Size", "930 × 400 × 4 mm"],
      ["Surface", "Micro-woven cloth"],
      ["RGB", "360° peripheral edge (iCUE)"],
      ["USB hub", "2 × USB-A pass-through"],
      ["Cable", "1.8 m braided USB-A"],
      ["Base", "Non-slip rubber"],
    ]),
    swatches: null,
  },
  {
    id: "asus-rog-claymore-ii-keycaps",
    sku: "HG-AC-005",
    catId: "accessories",
    catLabel: "Accessories",
    brand: "ASUS ROG",
    name: "Gaming Keycap Set PBT",
    fullName: "ASUS ROG Gaming Keycap Set PBT",
    blurb: "104+14 keys · PBT double-shot · ROG font",
    description:
      "Double-shot PBT keycaps that resist shine for years. ROG's keycap set includes 104 standard keys plus 14 additional gaming-layout replacements and a keycap puller. The PBT construction allows RGB light diffusion while keeping the legends crisp. Compatible with MX-style switches on any keyboard.",
    price: 49,
    msrp: 69,
    stock: "ok",
    stockLabel: "In Stock",
    quantity: 51,
    imageUrl: null,
    verified: false,
    badge: b("ignit", "SALE"),
    art: "controller",
    specs: sp([
      ["Keys included", "104 standard + 14 gaming"],
      ["Material", "PBT double-shot"],
      ["Profile", "OEM"],
      ["Compatibility", "MX-style switches"],
      ["Legends", "Backlit-compatible"],
      ["Extras", "Keycap puller included"],
    ]),
    swatches: sw({ Color: ["Black", "Cyber Text (White)"] }),
  },
];

async function main() {
  console.log("Deleting existing products…");
  const deleted = await prisma.product.deleteMany({});
  console.log(`  Removed ${deleted.count} product(s).`);

  console.log("Inserting catalog…");
  let inserted = 0;
  for (const p of products) {
    await prisma.product.create({
      data: {
        id: p.id,
        sku: p.sku,
        catId: p.catId,
        catLabel: p.catLabel,
        brand: p.brand,
        name: p.name,
        fullName: p.fullName,
        blurb: p.blurb,
        description: p.description,
        price: p.price,
        msrp: p.msrp ?? null,
        stock: p.stock,
        stockLabel: p.stockLabel,
        quantity: p.quantity,
        imageUrl: p.imageUrl ?? null,
        verified: p.verified,
        badge: p.badge ?? null,
        art: p.art,
        specs: p.specs,
        swatches: p.swatches ?? null,
      },
    });
    inserted++;
    process.stdout.write(`  ${inserted}/${products.length} — ${p.fullName}\n`);
  }

  // Update category counts
  const catCounts: Record<string, number> = {};
  for (const p of products) {
    catCounts[p.catId] = (catCounts[p.catId] ?? 0) + 1;
  }
  for (const [catId, count] of Object.entries(catCounts)) {
    await prisma.category.update({ where: { id: catId }, data: { count } });
  }
  console.log("  Category counts updated.");
  console.log(`\nDone — ${inserted} products seeded across ${Object.keys(catCounts).length} categories.`);
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(() => prisma.$disconnect());
